// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoykn9kP0mzH0zaZUprcSqRHRnYt4i2dk',
    appId: '1:503507364599:web:37da73292bdd9ca12081f2',
    messagingSenderId: '503507364599',
    projectId: 'bharath-flutter',
    authDomain: 'bharath-flutter.firebaseapp.com',
    storageBucket: 'bharath-flutter.appspot.com',
    measurementId: 'G-SY9ZW98QJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcL7jKJrKt-UaXFSHn1UAjxptLuXkayAk',
    appId: '1:503507364599:android:c7e87fa2de356a582081f2',
    messagingSenderId: '503507364599',
    projectId: 'bharath-flutter',
    storageBucket: 'bharath-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM07i3JPooF3iTpDgiKKbyOQrsaUzxpkU',
    appId: '1:503507364599:ios:da85441cdd315f1b2081f2',
    messagingSenderId: '503507364599',
    projectId: 'bharath-flutter',
    storageBucket: 'bharath-flutter.appspot.com',
    iosClientId:
        '503507364599-0ulgisqj3l9j4usr8knut2g2ig4ei0gp.apps.googleusercontent.com',
    iosBundleId: 'com.bharath.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM07i3JPooF3iTpDgiKKbyOQrsaUzxpkU',
    appId: '1:503507364599:ios:983e4bd5a4718ac72081f2',
    messagingSenderId: '503507364599',
    projectId: 'bharath-flutter',
    storageBucket: 'bharath-flutter.appspot.com',
    iosClientId:
        '503507364599-icj1p0j9j44qano284q6u8fep8ac4ts0.apps.googleusercontent.com',
    iosBundleId: 'com.bharath.mynotes.RunnerTests',
  );
}
